name: unicorn_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  animate_do: ^3.3.3

  cloud_firestore: ^4.15.1
  firebase_app_check: ^0.2.1+10
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.1
  firebase_database: ^10.4.3
  firebase_messaging: ^14.7.13
  firebase_storage: ^11.6.3

  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.1

  shared_preferences: ^2.2.2
  
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.2
  flutter_screenutil: ^5.9.0
  
  google_fonts: ^6.1.0
  flutter_otp_text_field: ^1.1.1
  phone_number_text_input_formatter: ^0.0.2
  
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  
  otp_text_field: ^1.1.3
  flutter_slidable: ^3.0.1
  fluro: ^2.0.5
  cached_network_image: ^3.3.1
  
  carousel_slider: ^4.2.1
  
  custom_button_builder: ^0.0.1
  intl: ^0.19.0
  
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  firebase_analytics: ^10.8.3
  flutter_svg: ^2.0.9
  palette_generator: ^0.3.3+3
  rive: ^0.12.4
  flutter_keyboard_visibility: ^6.0.0
  
  
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: InterThin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
